---
# handlers file for composer

- name: Install Composer
  block:
    - name: Install Composer via PHP
      ansible.builtin.command: >
        php /tmp/composer-setup.php --install-dir=/tmp --filename=composer.phar
        creates: /tmp/composer.phar
    - name: Copy composer
      ansible.builtin.copy:
        src: "/tmp/composer.phar"
        dest: "/usr/local/bin/composer"
        remote_src: true
        mode: "0755"
