---
# defaults file for deploy_server
system_require_packages:
  - "libfreetype6"
  - "libfreetype6-dev"
  - "zlib1g"
  - "zlib1g-dev"
  - "libxml2"
  - "libxml2-dev"
  - "libxslt1-dev"
  - "libxslt1.1"
  - "gcc"
  - "curl"
  - "make"
  - "libcurl4-openssl-dev"
  - "libssl-dev"
  - "mc"
  - "wget"
  - "aptitude"
  - "unzip"
  - "htop"
  - "nload"
  - "libffi-dev"
  - "gnupg2"
  - "pkg-config"
  - "tcl"
  - "git"
  - "sendmail"
  - "openssl"
  - "python3-minimal"
  - "python3-setuptools"
  - "screen"
  - "ethtool"
  - "openssl"
  - "nodejs"
  - "npm"
system_deploy_user: "deploy"
system_deploy_group: "deploy"
